version: '3.4'
services:

  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  grafana:
    image: grafana/grafana:7.5.0
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  alertmanager:
    image: prom/alertmanager:v0.27.0@sha256:e13b6ed5cb929eeaee733479dce55e10eb3bc2e9c4586c705a4e8da41e5eacf5
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    ports: 
      - "9100:9100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  blackbox_exporter: 
    image: prom/blackbox-exporter:v0.25.0@sha256:b04a9fef4fa086a02fc7fcd8dcdbc4b7b35cc30cdee860fdc6a19dd8b208d63e
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m

  loki:
    image: grafana/loki:2.9.10@sha256:35b02acc67654ddc38273e519b4f26f3967a907b9db5489af300c21f37ee1ae7
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m
  

  tempo:
    image: grafana/tempo:latest@sha256:7f90635cd02091d5d617a3f359e2343d2892c4326c463b31b6c2e47b39b140cb
    command: 
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/data/tempo/traces"   
      - "-storage.trace.wal.path=/data/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3100" 
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/storage:/data/tempo
    ports:
      - "14268"  # jaeger ingest
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  tempo-query:
    image: grafana/tempo-query:latest@sha256:e0559d0f0e4d2ef6fb3deacb226b5ac05b78ad26cac0233d2ba417d6473bb24b
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./tempo/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m
