x-default-logging: &logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: 2
    loki-max-backoff: 800ms
    loki-timeout: 1s

services:
  prometheus:
    image: prom/prometheus:v3.0.0-beta.0@sha256:064b379ac7f9d34c5b9b6cdd8c68a5706603270c0594bdefed67cd85c3b290be
    restart: always # To re-read the configuration file
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver,created-timestamp-zero-ingestion,native-histograms,promql-experimental-functions
    logging: *logging
    depends_on:
      - loki


  grafana:
    image: grafana/grafana:11.5.3@sha256:c319c1539496215b01b5f76294a3d200832322404b91731ca62ca5a9d24cdf7e
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging: *logging
    depends_on:
      - loki


  alertmanager:
    image: prom/alertmanager:v0.28.1@sha256:27c475db5fb156cab31d5c18a4251ac7ed567746a2483ff264516437a39b15ba
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging: *logging
    depends_on:
      - loki


  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.9.0@sha256:c99d7ee4d12a38661788f60d9eca493f08584e2e544bbd3b3fca64749f86b848
    ports: 
      - "9100:9100"
    logging: *logging
    depends_on:
      - loki


  blackbox_exporter: 
    image: prom/blackbox-exporter:v0.26.0@sha256:92e05d5fe0df01d3980518dc42f07b778a8997048b57392ebc7f7391ebd7bb06
    logging: *logging
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.4.2@sha256:58a6c186ce78ba04d58bfe2a927eff296ba733a430df09645d56cdc158f3ba08
    command: 
      - --config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    logging: *logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1@sha256:0076e6c250bef16968e29e8f94177b87b5a851c79ce14b270e657f5f655b9e04
    restart: always # To re-read the configuration file
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry-collector/config.yaml:/etc/otel-collector-config.yaml
    logging: *logging
    depends_on:
      - loki

  otel-collector-hostmetrics:
    image: otel/opentelemetry-collector-contrib:0.122.1@sha256:0076e6c250bef16968e29e8f94177b87b5a851c79ce14b270e657f5f655b9e04
    restart: always # To re-read the configuration file
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry-collector/hostmetrics.yaml:/etc/otel-collector-config.yaml
    logging: *logging
    depends_on:
      - loki












################
#
# OTEL-DEMO
#
################


  accountingservice:
    image: otel/demo:1.12.0-accountingservice@sha256:6d051840bb29d727d241d3b332f72a7023fa851c7a5075ba53286d0e80cfab33
    container_name: accounting-service
    restart: unless-stopped
    environment:
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=accountingservice
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      loki:
        condition: service_started
    logging: *logging

  kafka:
    image: otel/demo:2.0.2-kafka@sha256:0f1270d986ffd18ce73ca56e6c9b94077929fb31ae2be101036663213da0a4a1
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=kafka
      - KAFKA_HEAP_OPTS=-Xmx400m -Xms400m
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    logging: *logging
    depends_on:
      loki:
        condition: service_started

  
  # AdService
  adservice:
    image: otel/demo:1.12.0-adservice@sha256:a59e5eead495be5c2e559020d856e707e91856ddcbe3dba94a3333d390f8f104
    container_name: ad-service
    restart: unless-stopped
    environment:
      - AD_SERVICE_PORT=9555
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_SERVICE_NAME=adservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Cart service
  cartservice:
    image: otel/demo:1.12.0-cartservice@sha256:89730afa0b5d7f48de4db32b038b5228ce77a8914fe6156f09b944efb0bacf45
    container_name: cart-service
    restart: unless-stopped
    environment:
      - CART_SERVICE_PORT=7070
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - VALKEY_ADDR=valkey-cart:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=cartservice
      - ASPNETCORE_URLS=http://*:7070
    depends_on:
      valkey-cart:
        condition: service_started
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Checkout service
  checkoutservice:
    image: otel/demo:1.12.0-checkoutservice@sha256:380eccdc29e955eaa230ce4a702f3750d8ae398ddd4ea63320eba196f96da98b
    container_name: checkout-service
    restart: unless-stopped
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - CHECKOUT_SERVICE_PORT=5050
      - CART_SERVICE_ADDR=cartservice:7070
      - CURRENCY_SERVICE_ADDR=currencyservice:7001
      - EMAIL_SERVICE_ADDR=http://emailservice:6060
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50050
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=checkoutservice
    depends_on:
      cartservice:
        condition: service_started
      currencyservice:
        condition: service_started
      emailservice:
        condition: service_started
      paymentservice:
        condition: service_started
      productcatalogservice:
        condition: service_started
      shippingservice:
        condition: service_started
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Currency service
  currencyservice:
    image: otel/demo:1.12.0-currencyservice@sha256:db69fdf22ec59b2191ece2d00796eaca93639dce65d5de076b950b673bcffeaf
    container_name: currency-service
    restart: unless-stopped
    environment:
      - CURRENCY_SERVICE_PORT=7001
      - VERSION=1.11.1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo,service.name=currencyservice   # The C++ SDK does not support OTEL_SERVICE_NAME
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Email service
  emailservice:
    image: otel/demo:1.12.0-emailservice@sha256:a1f5cebb524000a5b41282e5e7ffad86bfe0b5bd376e6c56ca626a8fa91b4e3a
    container_name: email-service
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - EMAIL_SERVICE_PORT=6060
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=emailservice
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Fraud Detection service
  frauddetectionservice:
    image: otel/demo:1.12.0-frauddetectionservice@sha256:77cefdab4d5c9fe6d11da303ce533b615e4890d4015a26d9ea24ac7c704a44d6
    container_name: frauddetection-service
    restart: unless-stopped
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_INSTRUMENTATION_KAFKA_EXPERIMENTAL_SPAN_ATTRIBUTES=true
      - OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED=true
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=frauddetectionservice
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      loki:
        condition: service_started
    logging: *logging

  # Frontend
  frontend:
    image: otel/demo:2.0.2-frontend@sha256:3a0c7649f63d59656f6ba76fcd7ec79c1974cc3db0ae624efdf38fbdc8a14d4c
    container_name: frontend
    restart: unless-stopped
    environment:
      - PORT=8080
      - FRONTEND_ADDR=frontend:8080
      - AD_SERVICE_ADDR=adservice:9555
      - CART_SERVICE_ADDR=cartservice:7070
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - CURRENCY_SERVICE_ADDR=currencyservice:7001
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:9001
      - SHIPPING_SERVICE_ADDR=shippingservice:50050
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - ENV_PLATFORM=local
      - OTEL_SERVICE_NAME=frontend
      - PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/otlp-http/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - WEB_OTEL_SERVICE_NAME=frontend-web
      - OTEL_COLLECTOR_HOST=otel-collector
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      adservice:
        condition: service_started
      cartservice:
        condition: service_started
      checkoutservice:
        condition: service_started
      currencyservice:
        condition: service_started
      productcatalogservice:
        condition: service_started
      quoteservice:
        condition: service_started
      recommendationservice:
        condition: service_started
      shippingservice:
        condition: service_started
      otel-collector:
        condition: service_started
      imageprovider:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Frontend Proxy (Envoy)
  frontendproxy:
    image: otel/demo:1.12.0-frontendproxy@sha256:9fdec1be03e4695aec8c9eff3a2b3d6b854c1e25aa5677a373a63b17f42db743
    container_name: frontend-proxy
    restart: unless-stopped
    ports:
      - 84:8080
    environment:
      - FRONTEND_PORT=8080
      - FRONTEND_HOST=frontend:8080
      - LOCUST_WEB_HOST=loadgenerator
      - LOCUST_WEB_PORT=8089
      - GRAFANA_SERVICE_PORT=3000
      - GRAFANA_SERVICE_HOST=grafana
      - JAEGER_SERVICE_PORT=16686
      - JAEGER_SERVICE_HOST=jaeger
      - OTEL_COLLECTOR_HOST=otel-collector
      - IMAGE_PROVIDER_HOST=imageprovider
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_COLLECTOR_PORT_HTTP=4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - ENVOY_PORT=8080
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      frontend:
        condition: service_started
      loadgenerator:
        condition: service_started
      # jaeger:
      #   condition: service_started
      grafana:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Imageprovider
  imageprovider:
    image: otel/demo:1.12.0-imageprovider@sha256:4e322858fe56df702f5a35f18728fb47d176be3e752f380c9ffc456512a64565
    container_name: imageprovider
    restart: unless-stopped
    environment:
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_HOST=otel-collector
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_SERVICE_NAME=imageprovider
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Load Generator
  loadgenerator:
    image: otel/demo:1.12.0-loadgenerator@sha256:85c9935ff31b7ab575903fbd0b56a3161ec13e508966df25dc68fcfe7af5ec98
    container_name: load-generator
    restart: unless-stopped
    environment:
      - LOCUST_WEB_PORT=8089
      - LOCUST_USERS=10
      - LOCUST_HOST=loadgenerator
      - LOCUST_HEADLESS=false
      - LOCUST_AUTOSTART=true
      - LOCUST_BROWSER_TRAFFIC_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=loadgenerator
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - LOCUST_WEB_HOST=0.0.0.0
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      frontend:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Payment service
  paymentservice:
    image: otel/demo:1.12.0-paymentservice@sha256:b0f13eef3abf4025772b09b793621acee8f05138f55d00a38aaab27b1e0d44c4
    container_name: payment-service
    restart: unless-stopped
    environment:
      - PAYMENT_SERVICE_PORT=50051
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=paymentservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Product Catalog service
  productcatalogservice:
    image: otel/demo:1.12.0-productcatalogservice@sha256:008b9b662289b3ab498358e38b28e6bdaf706bfbe601041dfc7962bdd1d222c3
    container_name: product-catalog-service
    restart: unless-stopped
    environment:
      - PRODUCT_CATALOG_SERVICE_PORT=3550
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=productcatalogservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Quote service
  quoteservice:
    image: otel/demo:1.12.0-quoteservice@sha256:87eb325d306f972722dae536b45857cb5a5dcde0781f093e882be0e5b8313d9e
    container_name: quote-service
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - QUOTE_SERVICE_PORT=8090
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=quoteservice
      - OTEL_PHP_INTERNAL_METRICS_ENABLED=true
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Recommendation service
  recommendationservice:
    image: otel/demo:1.12.0-recommendationservice@sha256:b294a4278407716451b43758d89a952941f750ba2972d4a99d041c918233c58b
    container_name: recommendation-service
    restart: unless-stopped
    environment:
      - RECOMMENDATION_SERVICE_PORT=9001
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=recommendationservice
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      productcatalogservice:
        condition: service_started
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Shipping service
  shippingservice:
    image: otel/demo:1.12.0-shippingservice@sha256:a3ca4c02a5df456a8cfcf80f9bb5400ccb47c0d2f478e3a0e8472ce0753fccf0
    container_name: shipping-service
    restart: unless-stopped
    environment:
      - SHIPPING_SERVICE_PORT=50050
      - QUOTE_SERVICE_ADDR=http://quoteservice:8090
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=shippingservice
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # ******************
  # Dependent Services
  # ******************
  # Flagd, feature flagging service
  flagd:
    image: ghcr.io/open-feature/flagd:v0.12.2@sha256:2d3eb38ce3ad239db46ac8c4eb4686d4e53b308a09250d2eae4c33e63c044a9e
    container_name: flagd
    restart: unless-stopped
    environment:
      - FLAGD_OTEL_COLLECTOR_URI=otel-collector:4317
      - FLAGD_METRICS_EXPORTER=otel
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=flagd
    command: [
      "start",
      "--uri",
      "file:./etc/flagd/flagd.json"
    ]
    volumes:
      - ./flagd/flagd.json:/etc/flagd/flagd.json
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Valkey used by Cart service
  valkey-cart:
    image: valkey/valkey:8.1-alpine@sha256:d7cc7088a7e710cc815e8045f896739a0d1556457b78e16534ba2cfa3a783ada
    container_name: valkey-cart
    user: valkey
    restart: unless-stopped
    logging: *logging
    depends_on:
      loki:
        condition: service_started