x-default-logging: &logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: 2
    loki-max-backoff: 800ms
    loki-timeout: 1s

services:
  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    restart: always # To re-read the configuration file
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver,created-timestamp-zero-ingestion,native-histograms,promql-experimental-functions
    logging: *logging
    depends_on:
      - loki


  grafana:
    image: grafana/grafana:11.2.0@sha256:408afb9726de5122b00a2576763a8a57a3c86d5b0eff5305bc994ceb3eb96c3f
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging: *logging
    depends_on:
      - loki


  alertmanager:
    image: prom/alertmanager:v0.27.0@sha256:e13b6ed5cb929eeaee733479dce55e10eb3bc2e9c4586c705a4e8da41e5eacf5
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging: *logging
    depends_on:
      - loki


  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    ports: 
      - "9100:9100"
    logging: *logging
    depends_on:
      - loki


  blackbox_exporter: 
    image: prom/blackbox-exporter:v0.25.0@sha256:b04a9fef4fa086a02fc7fcd8dcdbc4b7b35cc30cdee860fdc6a19dd8b208d63e
    logging: *logging
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.1.1@sha256:e689cc634841c937de4d7ea6157f17e29cf257d6a320f1c293ab18d46cfea986
    command: 
      - --config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    logging: *logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0@sha256:af0f72b2d2493fc17f06cf3bc136548240cd7ebb2c8b1c8a7be6f3eb03068389
    restart: always # To re-read the configuration file
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry-collector/config.yaml:/etc/otel-collector-config.yaml
    logging: *logging
    depends_on:
      - loki

  otel-collector-hostmetrics:
    image: otel/opentelemetry-collector-contrib:0.109.0@sha256:af0f72b2d2493fc17f06cf3bc136548240cd7ebb2c8b1c8a7be6f3eb03068389
    restart: always # To re-read the configuration file
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry-collector/hostmetrics.yaml:/etc/otel-collector-config.yaml
    logging: *logging
    depends_on:
      - loki












################
#
# OTEL-DEMO
#
################


  accountingservice:
    image: otel/demo:1.11.1-accountingservice@sha256:f09dfbd4adf590fcf94070cb832583c1e9572edd558b1c5761429a14d7bf4d9e
    container_name: accounting-service
    restart: unless-stopped
    environment:
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=accountingservice
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      loki:
        condition: service_started
    logging: *logging

  kafka:
    image: otel/demo:1.11.1-kafka@sha256:7a967505ac81471e9cc1ccf4e0127ba1ee671f607be432ec2ff8cc259f99d9bf
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=kafka
      - KAFKA_HEAP_OPTS=-Xmx400m -Xms400m
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    logging: *logging
    depends_on:
      loki:
        condition: service_started

  
  # AdService
  adservice:
    image: otel/demo:1.11.1-adservice@sha256:509fb536e401d44128b95975fed58d8181a9f3104d17e50b645d6e531384bafb
    container_name: ad-service
    restart: unless-stopped
    environment:
      - AD_SERVICE_PORT=9555
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_SERVICE_NAME=adservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Cart service
  cartservice:
    image: otel/demo:1.11.1-cartservice@sha256:b4ff68be3ef54dfe365cfdab71f35332933f1f27121ef3a839299ad53c92a836
    container_name: cart-service
    restart: unless-stopped
    environment:
      - CART_SERVICE_PORT=7070
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - VALKEY_ADDR=valkey-cart:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=cartservice
      - ASPNETCORE_URLS=http://*:7070
    depends_on:
      valkey-cart:
        condition: service_started
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Checkout service
  checkoutservice:
    image: otel/demo:1.11.1-checkoutservice@sha256:d946019878299529d6272233daa8bc1e76d3ce4ddcee76448f14f8253c5d80e9
    container_name: checkout-service
    restart: unless-stopped
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - CHECKOUT_SERVICE_PORT=5050
      - CART_SERVICE_ADDR=cartservice:7070
      - CURRENCY_SERVICE_ADDR=currencyservice:7001
      - EMAIL_SERVICE_ADDR=http://emailservice:6060
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50050
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=checkoutservice
    depends_on:
      cartservice:
        condition: service_started
      currencyservice:
        condition: service_started
      emailservice:
        condition: service_started
      paymentservice:
        condition: service_started
      productcatalogservice:
        condition: service_started
      shippingservice:
        condition: service_started
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Currency service
  currencyservice:
    image: otel/demo:1.11.1-currencyservice@sha256:c6ad7f28380165c04849c142b978a4e1738078f776ad21cdcfc58de66e458ee6
    container_name: currency-service
    restart: unless-stopped
    environment:
      - CURRENCY_SERVICE_PORT=7001
      - VERSION=1.11.1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo,service.name=currencyservice   # The C++ SDK does not support OTEL_SERVICE_NAME
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Email service
  emailservice:
    image: otel/demo:1.11.1-emailservice@sha256:848727a693bde91351fda4eb036ec59642eee1ca9f3bc3d50ef96bc7c5004524
    container_name: email-service
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - EMAIL_SERVICE_PORT=6060
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=emailservice
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Fraud Detection service
  frauddetectionservice:
    image: otel/demo:1.11.1-frauddetectionservice@sha256:f3f73f902b94d5d399dbf418b11dbcafac6f2847a1b8299f09f76e0734e543c1
    container_name: frauddetection-service
    restart: unless-stopped
    environment:
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - KAFKA_SERVICE_ADDR=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_INSTRUMENTATION_KAFKA_EXPERIMENTAL_SPAN_ATTRIBUTES=true
      - OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED=true
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=frauddetectionservice
    depends_on:
      otel-collector:
        condition: service_started
      kafka:
        condition: service_healthy
      loki:
        condition: service_started
    logging: *logging

  # Frontend
  frontend:
    image: otel/demo:1.11.1-frontend@sha256:3e8d9efdbf7b17743400e6f570df302437bb99aae97ecc20ed2ff55a9d24bd39
    container_name: frontend
    restart: unless-stopped
    environment:
      - PORT=8080
      - FRONTEND_ADDR=frontend:8080
      - AD_SERVICE_ADDR=adservice:9555
      - CART_SERVICE_ADDR=cartservice:7070
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - CURRENCY_SERVICE_ADDR=currencyservice:7001
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:9001
      - SHIPPING_SERVICE_ADDR=shippingservice:50050
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - ENV_PLATFORM=local
      - OTEL_SERVICE_NAME=frontend
      - PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/otlp-http/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - WEB_OTEL_SERVICE_NAME=frontend-web
      - OTEL_COLLECTOR_HOST=otel-collector
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      adservice:
        condition: service_started
      cartservice:
        condition: service_started
      checkoutservice:
        condition: service_started
      currencyservice:
        condition: service_started
      productcatalogservice:
        condition: service_started
      quoteservice:
        condition: service_started
      recommendationservice:
        condition: service_started
      shippingservice:
        condition: service_started
      otel-collector:
        condition: service_started
      imageprovider:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Frontend Proxy (Envoy)
  frontendproxy:
    image: otel/demo:1.11.1-frontendproxy@sha256:146ea9519494f99c6d402d433cff29a70bae6598cbd6409fb5c063a220e21beb
    container_name: frontend-proxy
    restart: unless-stopped
    ports:
      - 84:8080
    environment:
      - FRONTEND_PORT=8080
      - FRONTEND_HOST=frontend:8080
      - LOCUST_WEB_HOST=loadgenerator
      - LOCUST_WEB_PORT=8089
      - GRAFANA_SERVICE_PORT=3000
      - GRAFANA_SERVICE_HOST=grafana
      - JAEGER_SERVICE_PORT=16686
      - JAEGER_SERVICE_HOST=jaeger
      - OTEL_COLLECTOR_HOST=otel-collector
      - IMAGE_PROVIDER_HOST=imageprovider
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_COLLECTOR_PORT_HTTP=4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - ENVOY_PORT=8080
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      frontend:
        condition: service_started
      loadgenerator:
        condition: service_started
      # jaeger:
      #   condition: service_started
      grafana:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Imageprovider
  imageprovider:
    image: otel/demo:1.11.1-imageprovider@sha256:e8acb917b786f3696ebf99e6cd9a1bed18d21a6853270a3afc4b6038d90afa82
    container_name: imageprovider
    restart: unless-stopped
    environment:
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_HOST=otel-collector
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_SERVICE_NAME=imageprovider
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Load Generator
  loadgenerator:
    image: otel/demo:1.11.1-loadgenerator@sha256:a95db305b4d0866b6637af1a45cc5b62355782d31c219b48360f104f43590c1e
    container_name: load-generator
    restart: unless-stopped
    environment:
      - LOCUST_WEB_PORT=8089
      - LOCUST_USERS=10
      - LOCUST_HOST=loadgenerator
      - LOCUST_HEADLESS=false
      - LOCUST_AUTOSTART=true
      - LOCUST_BROWSER_TRAFFIC_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=loadgenerator
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - LOCUST_WEB_HOST=0.0.0.0
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      frontend:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Payment service
  paymentservice:
    image: otel/demo:1.11.1-paymentservice@sha256:0a27cca2ef0f8d8cafcdff171620c30a14d2a2128c7c8bef4a8c0cca95b12e43
    container_name: payment-service
    restart: unless-stopped
    environment:
      - PAYMENT_SERVICE_PORT=50051
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=paymentservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Product Catalog service
  productcatalogservice:
    image: otel/demo:1.11.1-productcatalogservice@sha256:55a66eeb1aa320686fe6cfd84bb5fc5dac04b8fffe5333b8936126a64ed8d69a
    container_name: product-catalog-service
    restart: unless-stopped
    environment:
      - PRODUCT_CATALOG_SERVICE_PORT=3550
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=productcatalogservice
    depends_on:
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Quote service
  quoteservice:
    image: otel/demo:1.11.1-quoteservice@sha256:60758ab8a64b114d68b7dd5e5264525695fc54b3e239fe86d23accb5e135e184
    container_name: quote-service
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - QUOTE_SERVICE_PORT=8090
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=quoteservice
      - OTEL_PHP_INTERNAL_METRICS_ENABLED=true
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Recommendation service
  recommendationservice:
    image: otel/demo:1.11.1-recommendationservice@sha256:c57a5e4b0f72cb1cbc78670d2265f5007119a6575768500e4e196a547b1f0568
    container_name: recommendation-service
    restart: unless-stopped
    environment:
      - RECOMMENDATION_SERVICE_PORT=9001
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE=cumulative
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=recommendationservice
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      productcatalogservice:
        condition: service_started
      otel-collector:
        condition: service_started
      flagd:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Shipping service
  shippingservice:
    image: otel/demo:1.11.1-shippingservice@sha256:9d5f194e6f428bcfa5f1013d0e77510e669ba453539e77d6242ee669c19cc9c5
    container_name: shipping-service
    restart: unless-stopped
    environment:
      - SHIPPING_SERVICE_PORT=50050
      - QUOTE_SERVICE_ADDR=http://quoteservice:8090
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=shippingservice
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # ******************
  # Dependent Services
  # ******************
  # Flagd, feature flagging service
  flagd:
    image: ghcr.io/open-feature/flagd:v0.11.2@sha256:d9fea4520b79e786c63549e6820aaad95589385bee00e4389402b0a901840ced
    container_name: flagd
    restart: unless-stopped
    environment:
      - FLAGD_OTEL_COLLECTOR_URI=otel-collector:4317
      - FLAGD_METRICS_EXPORTER=otel
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=opentelemetry-demo
      - OTEL_SERVICE_NAME=flagd
    command: [
      "start",
      "--uri",
      "file:./etc/flagd/flagd.json"
    ]
    volumes:
      - ./flagd/flagd.json:/etc/flagd/flagd.json
    depends_on:
      otel-collector:
        condition: service_started
      loki:
        condition: service_started
    logging: *logging

  # Valkey used by Cart service
  valkey-cart:
    image: valkey/valkey:8.0-alpine@sha256:1f6b5c4df112ec869c17228911c6c33019b51756820a4432d423841eaf3c2fc7
    container_name: valkey-cart
    user: valkey
    restart: unless-stopped
    logging: *logging
    depends_on:
      loki:
        condition: service_started