version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
  grafana:
    image: grafana/grafana:7.2.1
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.0.1
  telegrambot: 
    image: metalmatze/alertmanager-bot:0.4.2
    command: 
    - --alertmanager.url=http://alertmanager:9093
    - --log.level=debug
    - --store=bolt
    - --bolt.path=/data/bog.db
    environment: 
      TELEGRAM_ADMIN: ${TELEGRAM_ADMIN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes: 
      - ./alertmanager-bot/storage:/data
  # process_exporter:
  #   user: "1000:1000"
  #   privileged: true
  #   image: arthursens/process-exporter
  #   volumes: 
  #   - /proc:/host/proc
  #   command:
  #   - --procfs
  #   - /host/proc
  #   - -config.path
  #   - /config/config.yml
