services:

  prometheus:
    image: prom/prometheus:v2.54.1@sha256:f6639335d34a77d9d9db382b92eeb7fc00934be8eae81dbc03b31cfe90411a94
    restart: always # To re-read the configuration file
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
      - --web.enable-remote-write-receiver
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  grafana:
    image: grafana/grafana:11.2.0@sha256:408afb9726de5122b00a2576763a8a57a3c86d5b0eff5305bc994ceb3eb96c3f
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  alertmanager:
    image: prom/alertmanager:v0.27.0@sha256:e13b6ed5cb929eeaee733479dce55e10eb3bc2e9c4586c705a4e8da41e5eacf5
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.8.2@sha256:4032c6d5bfd752342c3e631c2f1de93ba6b86c41db6b167b9a35372c139e7706
    ports: 
      - "9100:9100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  blackbox_exporter: 
    image: prom/blackbox-exporter:v0.25.0@sha256:b04a9fef4fa086a02fc7fcd8dcdbc4b7b35cc30cdee860fdc6a19dd8b208d63e
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m

  loki:
    image: grafana/loki:2.9.10@sha256:35b02acc67654ddc38273e519b4f26f3967a907b9db5489af300c21f37ee1ae7
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0@sha256:923eb1cfae32fe09676cfd74762b2b237349f2273888529594f6c6ffe1fb3d7e
    restart: always # To re-read the configuration file
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry-collector/config.yaml:/etc/otel-collector-config.yaml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m