version: '3.4'
services:

  prometheus:
    image: prom/prometheus:v2.22.0
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/rules:/etc/prometheus/rules
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  grafana:
    image: grafana/grafana:7.3.0-beta1
    user: "1000:1000"
    ports: 
      - 82:3000
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports: 
      - 83:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    volumes: 
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.0.1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  telegrambot: 
    #image: metalmatze/alertmanager-bot:0.4.2
    image: telegrambot # built from https://github.com/ArthurSens/alertmanager-bot -> branch 'tracing support'
    command: 
    - --alertmanager.url=http://alertmanager:9093
    - --log.level=debug
    - --store=bolt
    - --bolt.path=/data/bog.db
    environment: 
      TELEGRAM_ADMIN: ${TELEGRAM_ADMIN}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      JAEGER_AGENT_HOST: tempo
      JAEGER_ENDPOINT: tempo:14268 # send traces to Tempo
      # JAEGER_ENDPOINT: http://tempo:14268/api/traces # send traces to Tempo
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    volumes: 
      - ./alertmanager-bot/storage:/data
    ports: 
      - "8080:8080"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  loki:
    image: grafana/loki:2.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m
  

  tempo:
    image: grafana/tempo:latest
    command: 
      - "-storage.trace.backend=local"                  # tell tempo where to permanently put traces
      - "-storage.trace.local.path=/tmp/tempo/traces"   
      - "-storage.trace.wal.path=/tmp/tempo/wal"        # tell tempo where to store the wal
      - "-auth.enabled=false"                           # disables the requirement for the X-Scope-OrgID header
      - "-server.http-listen-port=3100" 
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - /tmp/tempo:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m


  tempo-query:
    image: grafana/tempo-query:latest
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./tempo/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
        mode: non-blocking
        max-buffer-size: 4m
