version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.22.0
    user: "1000:1000"
    ports:
      - 81:9090
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/storage:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api 
      - --web.enable-lifecycle
      - --storage.tsdb.retention.time=2d
  grafana:
    image: grafana/grafana:7.2.1
    user: "1000:1000"
    ports: 
      - 82:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports: 
      - 83:9093
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
  node_exporter:
    privileged: true
    image: prom/node-exporter:v1.0.1
