dist:
  module: github.com/arthursens/home-monitoring/cmd/home-monitoring-otelcol
  name: home-monitoring-otelcol
  description: Custom OpenTelemetry Collector distribution for the home monitoring stack.
  output_path: ./opentelemetry-collector/_build
  version: 0.152.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/pprofreceiver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/receivercreator v0.154.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.154.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.154.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.154.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer/dockerobserver v0.154.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.154.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.60.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.60.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.60.0

telemetry:
  gomod: go.opentelemetry.io/collector/service v0.154.0
  import: go.opentelemetry.io/collector/service/telemetry/otelconftelemetry
