receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  hostmetrics:
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:


exporters:
  # prometheusremotewrite:
  #   endpoint: http://prometheus:9090/api/v1/write
  # The Prometheus exporter gather all metrics from previous pipeline and exposes them in the desired port.
  # One advantage over the Prometheus remote write exporter is includes metadata.
  prometheus:
    endpoint: 0.0.0.0:8889 
   

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      # exporters: [prometheusremotewrite]
      exporters: [prometheus]