global:
  scrape_interval: 30s 

rule_files:
- /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs: 
      - targets: ['node_exporter:9100']

  - job_name: 'tracing'
    static_configs: 
      - targets: ['tempo:3100', 'loki:3100']

  # - job_name: 'process_exporter'
  #   static_configs: 
  #     - targets: ['process_exporter:9256']
