global:
  scrape_interval: 60s 

storage:
  tsdb:
    out_of_order_time_window: 30m

otlp:
  promote_resource_attributes:
  - service.instance.id
  - service.name
  - service.namespace
  - service.version
  - deployment.environment
  - deployment.environment.name
  - container.name
  keep_identifying_resource_attributes: true

tracing:
  client_type: grpc
  endpoint: otel-collector:4317
  insecure: true
  sampling_fraction: 1.0

rule_files:
- /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
