apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    nodeGraph:
      enabled: true
    search:
      hide: false
    serviceMap:
      datasourceUid: prometheus
    traceQuery:
      timeShiftEnabled: true
      spanStartTimeShift: -1h
      spanEndTimeShift: 1h
    tracesToLogsV2:
      datasourceUid: loki
      spanStartTimeShift: -1h
      spanEndTimeShift: 1h
      filterByTraceID: true
      filterBySpanID: false
    tracesToMetrics:
      datasourceUid: prometheus
      spanStartTimeShift: -1h
      spanEndTimeShift: 1h
      tags:
        - key: service.name
          value: service
      queries:
        - name: Span rate
          query: sum(rate(traces_spanmetrics_calls_total{$$__tags}[5m]))
    tracesToProfiles:
      datasourceUid: pyroscope
      profileTypeId: process_cpu:cpu:nanoseconds:cpu:nanoseconds
      tags:
        - key: service.name
          value: service_name
