groups: 
- name: myNotebook #yamllint disable-line
  rules: 

  # I have a really small SSD, no HD
  # Disk usage always annoy me
  - alert: DiskUsage
    expr: avg(100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)) > 95
    for: 5m
    labels: 
      severity: warning
    annotations:
      description: "Disk usage is almost full."

  # My battery is not the best and I leave my notebook off the charge quite often
  - alert: PowerSupplyOff
    expr: node_power_supply_online == 0
    for: 30s # testing tracing at telegrambot
    labels:
      severity: critical
    annotations:
      description: "Notebook is not charging for way too long."

  # I usually work while sunbathing B)  But hardware can heat up quickly
  - alert: HardwareHeatingUp
    expr: node_hwmon_temp_celsius > node_hwmon_temp_crit_celsius * 0.8
    for: 5m
    labels:
      severity: critical
    annotations: 
      description: "Hardware is heating up. Get the f*** out of the sun."
