server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

metrics_generator:
  processor:
    service_graphs:
      dimensions:
        - service.namespace
        - deployment.environment
        - deployment.environment.name
        - grafana.host.id
      enable_client_server_prefix: true
    span_metrics:
      dimensions:
        - service.namespace
        - deployment.environment
        - deployment.environment.name
        - grafana.host.id
      enable_target_info: true
      enable_instance_label: true
    host_info:
      host_identifiers:
        - k8s.node.name
        - host.id
        - grafana.host.id
  storage:
    path: /var/tempo/generator/wal
    remote_write_add_org_id_header: false
    remote_write:
      - url: http://prometheus:9090/api/v1/write

backend_scheduler:
  provider:
    compaction:
      compaction:
        block_retention: 24h

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - host-info
